apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: "prod"
  CONFIG_SERVER_URL: "http://config-service:8888"
  SPRING_APPLICATION_NAME: "user-management-service"
  PROD_DB_URL: "jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
